### ISSUE TITLE
Adapter terminates because of Type Error

### ISSUE THREAD

**Issue by marian-t-web-de** [iobroker-community-adapters/ioBroker.accuweather#281]
**Describe the bug**  
Adapter repatly terminates because of Type Error, see iObroker log below.

**To Reproduce**  
1. Go to iObroker log
2. Select accuweather
3.  See error
`TypeError: Cannot read properties of undefined (reading 'statusCode') at Request._callback (/opt/iobroker/node_modules/iobroker.accuweather/lib/accuapi.js:88:9) at self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at Request.emit (node:events:513:28) at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8) at ClientRequest.emit (node:events:513:28) at Socket.socketErrorListener (node:_http_client:494:9) at Socket.emit (node:events:513:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21)`
**Expected behavior**  
No error

**Screenshots & Logfiles**  
<img width="768" alt="image" src="https://github.com/iobroker-community-adapters/ioBroker.accuweather/assets/37208979/5a58ae53-e3d0-422d-89f2-c37225f2e2c5">

**Versions:**  
 - Adapter version: 1.2.4
Plattform linux
Betriebssystem linux
Architektur arm
CPUs 4
Geschwindigkeit 1500 MHz
Modell ARMv7 Processor rev 3 (v7l)
RAM 3.75 GB
System-Betriebszeit 41 T. 15:18:05
Node.js v16.19.1 (Es gibt eine neuere Version: v16.20.2 - Empfohlene Version v18.17.1)
time 1693466770529 
timeOffset -120
Anzahl der Adapter 493
NPM 9.5.1
Datenträgergröße 28.14 GB
freier Festplattenspeicher 19.93 GB
Betriebszeit 41 T. 15:17:46
Aktive Instanzen 24
Weg /opt/iobroker/
Hostname raspberrypi

**Additional context**

**Comment by marian-t-web-de** [comment]
I‘m glad I could help to improve Your software.
